[package]
name = "malloced"
version = "0.0.0"
authors = ["Nikolai Vazquez <hello@nikolaivazquez.com>"]
categories = ["no-std", "memory-management", "api-bindings"]

[features]
default = ["std"]
std = []
pin = [] # MSRV: 1.33
